### ISSUE TITLE
Unable to train

### ISSUE THREAD

**Issue by sanjay-391** [Lvfeifan/MBLLEN#7]
![image](https://user-images.githubusercontent.com/60467695/80506407-28725200-8993-11ea-8441-1f7d5804e3a3.png)

I'm unable to train the model. Its stuck for ever as shown in this pic. I tried reducing the learning rate, reduced the training samples, epoch =2. its not even completing 1 epoch

**Comment by 1900141** [comment]
Excuse me. I had the same problem as you when I was training my code.
Have you solved your problem?

**Comment by Sherlock-hh** [comment]
> 

hello  i met the same problem ,did u solved it? can you help me?
