### ISSUE TITLE
When Training, loss and bright_mse is NAN and bright_psnr is INF

### ISSUE THREAD

**Issue by huwenyue** [Lvfeifan/MBLLEN#8]
When Training, it shows loss: 0.0000e+00 - bright_mae: 0.0000e+00 - bright_mse: 0.0000e+00 - bright_psnr: inf - bright_SSIM: 1.0000 - bright_AB: 0.0000e+00 - LR =  0.0009900001
The loss is very strange, and I don't know why? 
Then Batch 0: Invalid loss, terminating training

**Comment by yanmenglu** [comment]
hello, I have one problem， could you help me. when I  train the MBLLen model, which used CPU not GPU.how I solve this problem.
